### PR TITLE
added dither effect, BrushCollection and AlphaAdjustment plugin

### PR DESCRIPTION
**Pull request by codeprof**

### CODE REVIEW

**Comment by robpvn** [comment]
New addins, great! There's just one thing missing here; like it says in the readme you have to run the update script so that the indexes will shoiw the new addins: `Run "update_repository.sh" to regenerate the add-in index.` Do that and I'll happily merge this PR. :+1:

**Comment by codeprof** [comment]
so, hope I did everything correctly now :-)
Thank you

**Comment by robpvn** [comment]
Looks good to me, thanks!

**Comment by Imerion** [comment]
Cool! Nice to see new things happen with this project! (Noticed some really nice activity on the main Pinta git too) It's a great program, and everyone involved should have a big thanks!

**Pull request merged**
